version: '2.3'
# services:
#   app:
#     container_name: go-first-api-container
#     # tty: true
#     image: brando/go/first-api
#     ports:
#       - 3000:3000
#     restart: on-failure
#     volumes:
#       - ./:/app
services:
  my-project-with-air:
    image: cosmtrek/air
    # working_dir value has to be the same of mapped volume
    working_dir: /app-inside-docker
    ports:
      - 3000:3000
    # environment:
    #   - ENV_A=${ENV_A}
    #   - ENV_B=${ENV_B}
    #   - ENV_C=${ENV_C}
    volumes:
      - ./:/app-inside-docker/