apiVersion: v1
kind: Service
metadata:
  name: go-first-api-srv
spec:
  type: NodePort
  selector:
    pod-label: go-first-api-pod 
  ports:
    - name: go-first-api-srv
      protocol: TCP
      port: 3000 # Service port
      targetPort: 3000 # Pod port